name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deployment on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to Server (Port 4106)
        run: |
          ssh -o StrictHostKeyChecking=no wodo-deploy@deploy.wodo.digital -p 4106 "
            cd /home/wodo-deploy/htdocs/deploy.wodo.digital && \
            git pull origin main && \
            npm install && \
            npm run build && \
            pm2 restart next-deploy
          "
